id: I04BB0AB5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:48:52+00:00'
last_modified: '2022-06-09T07:55:39.039501+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4428
  title: དབུ་མའི་དོགས་གཅོད་རྟེན་འབྱུང་སྙིང་པོ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B839:
      image_group_id: I1KG4442
      title: Volume 1 of dbu ma'i dogs gcod rten 'byung snying po
      total_pages: 422
      order: 1
      base_file: B839.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
