id: P007952
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4428
  title: དབུ་མའི་དོགས་གཅོད་རྟེན་འབྱུང་སྙིང་པོ་
  author: ''
  volumes:
    233754cebde744109e90dfc87a01dada:
      image_group_id: I1KG4442
      title: ''
      volume_number: 1
      total_pages: 422
ebook_metadata:
  title: དབུ་མའི་དོགས་གཅོད་རྟེན་འབྱུང་སྙིང་པོ་
  author: ''
  sku: P007952
  cover: cover.jpg
  layers:
  - pagination
